name: Reusable Workflow To Deploy MuleSoft Application

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_sha: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Danypoint.username=76f002fff9c041d78a663b0a26bc008f \
          -Danypoint.password=a8055e977df843bCB9fFB5683E52A9BA

      - name: Get commit SHA
        id: get_sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  tagversion:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      # - name: Create and push tag
      #   run: |
      #     VERSION_TAG="build-$(date +'%Y%m%d-%H%M%S')"
      #     git config --global user.email "github-actions@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git tag $VERSION_TAG
      #     git push origin $VERSION_TAG
      - name: Create and push version tag
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION_TAG="v$VERSION"
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag $VERSION_TAG
          git push origin $VERSION_TAG


  deploydev:
    needs: tagversion
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Deploy to dev
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Danypoint.username=76f002fff9c041d78a663b0a26bc008f \
          -Danypoint.password=a8055e977df843bCB9fFB5683E52A9BA \
          -Danypoint.businessGroup=a62f6236-0b02-4e5f-a8eb-dc5e37aedb12 \
          -Denv=Dev \
          -Dappname=health-check-dev \
          -Danypoint.platform.client_id=777df98bcd084a75bfe4b973a9e53516  \
          -Danypoint.platform.client_secret=AF10d59Ee8C64EFb85BCc8474b2aA7eD \
          -Dmule.env=dev \
          -Dkey=mule

  deployuat:
    needs: deploydev
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Deploy to uat
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Danypoint.username=76f002fff9c041d78a663b0a26bc008f \
          -Danypoint.password=a8055e977df843bCB9fFB5683E52A9BA \
          -Danypoint.businessGroup=a62f6236-0b02-4e5f-a8eb-dc5e37aedb12 \
          -Denv=UAT \
          -Dappname=health-check-uat \
          -Danypoint.platform.client_id=b5b72434253f480c8405d9cb8d853fed \
          -Danypoint.platform.client_secret=d7d4Ff82Be8f49949661Ffd3ED535D46 \
          -Dmule.env=qa \
          -Dkey=mule 

  deployprod:
    needs: deployuat
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Deploy to prod
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
          -Danypoint.username=76f002fff9c041d78a663b0a26bc008f \
          -Danypoint.password=a8055e977df843bCB9fFB5683E52A9BA \
          -Danypoint.businessGroup=a62f6236-0b02-4e5f-a8eb-dc5e37aedb12 \
          -Denv=PROD \
          -Dappname=health-check-prod \
          -Danypoint.platform.client_id=777df98bcd084a75bfe4b973a9e53516  \
          -Danypoint.platform.client_secret=AF10d59Ee8C64EFb85BCc8474b2aA7eD \
          -Dmule.env=prod \
          -Dkey=mule 
